const texts = {
    en: {
        firstPageButton: 'First',
        lastPageButton: 'Last',
        nextPageButton: 'Next',
        previousPageButton: 'Previous',
        toolsButton: 'Tools',
        pageInput: 'Page number',
        goToPageButton: 'Go to',
        downloadButton: 'Download',
        sketchVerButton: 'Sketch',
        sketchVerButtonAlt: 'Return',
        originalSizeOption: 'Original',
        pageOptionsTitle: 'Page options',
        findPageTitle: 'Find page',
        removePageGlowButton: 'Disable page glow',
        removePageGlowButtonAlt: 'Enable page glow',
        license: 'TWOKINDS, its logo, and all related characters are copyright © 2024 Thomas J. Fischbach. All rights reserved.',
        pageViewerButton: 'Page viewer',
        pageViewerButtonDesc: 'Continue reading: Page ',
        archiveButton: 'Archive',
        archiveButtonDesc: 'Browse through the comic pages archive',
        galleryButton: 'Gallery',
        galleryButtonDesc: 'Explore all Twokinds-related artwork',
        wikiButton: 'Wiki',
        wikiButtonDesc: 'Dive into the Twokinds universe with the community wiki',
        aboutButton: 'About',
        aboutButtonDesc: 'Learn more about the comic and this website',
        discordButton: 'Discord',
        discordButtonDesc: 'Join the Twokinds fan community in Discord',
        disableSwipesButton: 'Disable swipes',
        disableSwipesButtonAlt: 'Enable swipes',
        disableMarginsButton: 'Disable margins',
        disableMarginsButtonAlt: 'Enable margins'
    },
    
    ru: {
        firstPageButton: 'Первая',
        lastPageButton: 'Последняя',
        nextPageButton: 'Следующая',
        previousPageButton: 'Предыдущая',
        toolsButton: 'Инструменты',
        pageInput: 'Номер страницы',
        goToPageButton: 'Перейти',
        downloadButton: 'Скачать',
        sketchVerButton: 'Эскиз',
        sketchVerButtonAlt: 'Вернуться',
        originalSizeOption: 'Оригинал',
        pageOptionsTitle: 'Настройки страницы',
        findPageTitle: 'Найти страницу',
        removePageGlowButton: 'Отключить подсветку страницы',
        removePageGlowButtonAlt: 'Включить подсветку страницы',
        license: 'TWOKINDS, его логотип и все связанные с ним персонажи являются объектом авторского права © 2024 Томас Дж. Фишбах. Все права защищены.',
        pageViewerButton: 'Просмотр страниц',
        pageViewerButtonDesc: 'Продолжить чтение: Страница ',
        archiveButton: 'Архив',
        archiveButtonDesc: 'Просмотр архива страниц комиксов',
        galleryButton: 'Галерея',
        galleryButtonDesc: 'Изучите все произведения, связанные с Twokinds',
        wikiButton: 'Вики',
        wikiButtonDesc: 'Погрузитесь во вселенную Twokinds с помощью вики-сообщества',
        aboutButton: 'О нас',
        aboutButtonDesc: 'Узнайте больше о комиксе и этом сайте',
        discordButton: 'Discord',
        discordButtonDesc: 'Присоединяйтесь к фанатскому сообществу Twokinds в Discord',
        disableSwipesButton: "Отключить жесты",
        disableSwipesButtonAlt: "Включить жесты",
        disableMarginsButton: "Отключить отступы",
        disableMarginsButtonAlt: "Включить отступы"
    },
    
    be: {
        firstPageButton: 'Першая',
        lastPageButton: 'Апошняя',
        nextPageButton: 'Наступная',
        previousPageButton: 'Папярэдняя',
        toolsButton: 'Інструменты',
        pageInput: 'Нумар старонкі',
        goToPageButton: 'Перайсці',
        downloadButton: 'Спампаваць',
        sketchVerButton: 'Эскіз',
        sketchVerButtonAlt: 'Вярнуцца',
        originalSizeOption: 'Арыгінал',
        pageOptionsTitle: "Опцыі старонкі",
        findPageTitle: "Знайсці старонку",
        removePageGlowButton: 'Адключыць падсвятленне старонкі',
        removePageGlowButtonAlt: 'Уключыць падсвятленне старонкі',
        license: 'TWOKINDS, яго лагатып і ўсе звязаныя з ім персанажы абаронены аўтарскім правам © 2024 Томас Дж. Фішбах. Усе правы абаронены.',
        pageViewerButton: 'Прагляд старонак',
        pageViewerButtonDesc: 'Працягнуць чытанне: Старонка ',
        archiveButton: 'Архіў',
        archiveButtonDesc: 'Прагляд архіва старонак коміксаў',
        galleryButton: 'Галерэя',
        galleryButtonDesc: 'Вывучыць усе працы, звязаныя з Twokinds',
        wikiButton: 'Вікі',
        wikiButtonDesc: 'Пагрузіцеся ў сусвет Twokinds з дапамогай вікі-супольнасці',
        aboutButton: 'Пра нас',
        aboutButtonDesc: 'Даведайцеся больш пра комікс і гэты сайт',
        discordButton: 'Discord',
        discordButtonDesc: 'Далучайцеся да фанатскай супольнасці Twokinds у Discord',
        disableSwipesButton: "Адключыць жэсты",
        disableSwipesButtonAlt: "Уключыць жэсты",
        disableMarginsButton: "Адключыць адступы",
        disableMarginsButtonAlt: "Уключыць адступы"
    },

    it: {
        firstPageButton: 'Prima',
        lastPageButton: 'Ultima',
        nextPageButton: 'Successiva',
        previousPageButton: 'Precedente',
        toolsButton: 'Strumenti',
        pageInput: 'Numero di pagina',
        goToPageButton: 'Vai a',
        downloadButton: 'Scarica',
        sketchVerButton: 'Schizzo',
        sketchVerButtonAlt: 'Ritorna',
        originalSizeOption: 'Originale',
        pageOptionsTitle: 'Opzioni di pagina',
        findPageTitle: 'Trova pagina',
        removePageGlowButton: 'Disattiva bagliore pagina',
        removePageGlowButtonAlt: 'Attiva bagliore pagina',
        license: 'TWOKINDS, il suo logo e tutti i personaggi correlati sono protetti da copyright © 2024 Thomas J. Fischbach. Tutti i diritti riservati.',
        pageViewerButton: 'Visualizzatore di pagine',
        pageViewerButtonDesc: 'Continua a leggere: Pagina ',
        archiveButton: 'Archivio',
        archiveButtonDesc: 'Sfoglia l\'archivio delle pagine del fumetto',
        galleryButton: 'Galleria',
        galleryButtonDesc: 'Esplora tutte le opere correlate a Twokinds',
        wikiButton: 'Wiki',
        wikiButtonDesc: 'Immergiti nell\'universo di Twokinds con la wiki della comunità',
        aboutButton: 'Informazioni',
        aboutButtonDesc: 'Scopri di più sul fumetto e su questo sito web',
        discordButton: 'Discord',
        discordButtonDesc: 'Unisciti alla comunità di fan di Twokinds su Discord',
        disableSwipesButton: "Disabilita scorrimenti",
        disableSwipesButtonAlt: "Abilita scorrimenti",
        disableMarginsButton: "Disabilita margini",
        disableMarginsButtonAlt: "Abilita margini"
    },
    
    fr: {
        firstPageButton: 'Première',
        lastPageButton: 'Dernière',
        nextPageButton: 'Suivante',
        previousPageButton: 'Précédente',
        toolsButton: 'Outils',
        pageInput: 'Numéro de page',
        goToPageButton: 'Aller à',
        downloadButton: 'Télécharger',
        sketchVerButton: 'Esquisse',
        sketchVerButtonAlt: 'Retour',
        originalSizeOption: 'Original',
        pageOptionsTitle: 'Options de page',
        findPageTitle: 'Trouver page',
        removePageGlowButton: 'Désactiver la lueur de la page',
        removePageGlowButtonAlt: 'Activer la lueur de la page',
        license: 'TWOKINDS, son logo et tous les personnages associés sont protégés par copyright © 2024 Thomas J. Fischbach. Tous droits réservés.',
        pageViewerButton: 'Visionneuse de pages',
        pageViewerButtonDesc: 'Continuer la lecture : Page ',
        archiveButton: 'Archive',
        archiveButtonDesc: 'Parcourir les pages d\'archive des bandes dessinées',
        galleryButton: 'Galerie',
        galleryButtonDesc: 'Explorez toutes les œuvres liées à Twokinds',
        wikiButton: 'Wiki',
        wikiButtonDesc: 'Plongez dans l\'univers de Twokinds avec le wiki communautaire',
        aboutButton: 'À propos',
        aboutButtonDesc: 'En savoir plus sur la bande dessinée et ce site',
        discordButton: 'Discord',
        discordButtonDesc: 'Rejoignez la communauté de fans de Twokinds sur Discord',
        disableSwipesButton: "Désactiver les balayages",
        disableSwipesButtonAlt: "Activer les balayages",
        disableMarginsButton: "Désactiver les marges",
        disableMarginsButtonAlt: "Activer les marges"
    },
    
    es: {
        firstPageButton: 'Primera',
        lastPageButton: 'Última',
        nextPageButton: 'Siguiente',
        previousPageButton: 'Anterior',
        toolsButton: 'Herramientas',
        pageInput: 'Número de página',
        goToPageButton: 'Ir a',
        downloadButton: 'Descargar',
        sketchVerButton: 'Bosquejo',
        sketchVerButtonAlt: 'Regresar',
        originalSizeOption: 'Original',
        pageOptionsTitle: 'Opciones de página',
        findPageTitle: 'Encontrar página',
        removePageGlowButton: 'Desactivar brillo de la página',
        removePageGlowButtonAlt: 'Activar brillo de la página',
        license: 'TWOKINDS, su logotipo y todos los personajes relacionados están protegidos por derechos de autor © 2024 Thomas J. Fischbach. Todos los derechos reservados.',
        pageViewerButton: 'Visor de páginas',
        pageViewerButtonDesc: 'Continuar leyendo: Página ',
        archiveButton: 'Archivo',
        archiveButtonDesc: 'Navegar por el archivo de páginas del cómic',
        galleryButton: 'Galería',
        galleryButtonDesc: 'Explora todas las obras relacionadas con Twokinds',
        wikiButton: 'Wiki',
        wikiButtonDesc: 'Sumérgete en el universo de Twokinds con la wiki comunitaria',
        aboutButton: 'Acerca de',
        aboutButtonDesc: 'Aprende más sobre el cómic y este sitio web',
        discordButton: 'Discord',
        discordButtonDesc: 'Únete a la comunidad de fans de Twokinds en Discord',
        disableSwipesButton: "Desactivar deslizamientos",
        disableSwipesButtonAlt: "Activar deslizamientos",
        disableMarginsButton: "Desactivar márgenes",
        disableMarginsButtonAlt: "Activar márgenes"
    },
    
    de: {
        firstPageButton: 'Erste',
        lastPageButton: 'Letzte',
        nextPageButton: 'Nächste',
        previousPageButton: 'Vorherige',
        toolsButton: 'Werkzeuge',
        pageInput: 'Seitenzahl',
        goToPageButton: 'Gehe zu',
        downloadButton: 'Herunterladen',
        sketchVerButton: 'Skizze',
        sketchVerButtonAlt: 'Zurück',
        originalSizeOption: 'Original',
        pageOptionsTitle: 'Seitenoptionen',
        findPageTitle: 'Seite finden',
        removePageGlowButton: 'Seitenleuchten deaktivieren',
        removePageGlowButtonAlt: 'Seitenleuchten aktivieren',
        license: 'TWOKINDS, sein Logo und alle verwandten Charaktere sind urheberrechtlich geschützt © 2024 Thomas J. Fischbach. Alle Rechte vorbehalten.',
        pageViewerButton: 'Seitenansicht',
        pageViewerButtonDesc: 'Weiterlesen: Seite ',
        archiveButton: 'Archiv',
        archiveButtonDesc: 'Durchsuchen Sie das Comicseiten-Archiv',
        galleryButton: 'Galerie',
        galleryButtonDesc: 'Erkunden Sie alle Twokinds-bezogenen Kunstwerke',
        wikiButton: 'Wiki',
        wikiButtonDesc: 'Tauchen Sie ein in das Twokinds-Universum mit dem Community-Wiki',
        aboutButton: 'Über',
        aboutButtonDesc: 'Erfahren Sie mehr über den Comic und diese Website',
        discordButton: 'Discord',
        discordButtonDesc: 'Treten Sie der Twokinds-Fangemeinde bei Discord bei',
        disableSwipesButton: "Wischen deaktivieren",
        disableSwipesButtonAlt: "Wischen aktivieren",
        disableMarginsButton: "Ränder deaktivieren",
        disableMarginsButtonAlt: "Ränder aktivieren"
    },

    pt: {
        firstPageButton: 'Primeira',
        lastPageButton: 'Última',
        nextPageButton: 'Próxima',
        previousPageButton: 'Anterior',
        toolsButton: 'Ferramentas',
        pageInput: 'Número da página',
        goToPageButton: 'Ir para',
        downloadButton: 'Baixar',
        sketchVerButton: 'Esboço',
        sketchVerButtonAlt: 'Voltar',
        originalSizeOption: 'Original',
        pageOptionsTitle: 'Opções de página',
        findPageTitle: 'Encontrar página',
        removePageGlowButton: 'Desativar brilho da página',
        removePageGlowButtonAlt: 'Ativar brilho da página',
        license: 'TWOKINDS, seu logotipo e todos os personagens relacionados são protegidos por direitos autorais © 2024 Thomas J. Fischbach. Todos os direitos reservados.',
        pageViewerButton: 'Visualizador de Páginas',
        pageViewerButtonDesc: 'Continuar a leitura: Página ',
        archiveButton: 'Arquivo',
        archiveButtonDesc: 'Navegue pelo arquivo de páginas de quadrinhos',
        galleryButton: 'Galeria',
        galleryButtonDesc: 'Explore todas as obras relacionadas ao Twokinds',
        wikiButton: 'Wiki',
        wikiButtonDesc: 'Mergulhe no universo Twokinds com o wiki da comunidade',
        aboutButton: 'Sobre',
        aboutButtonDesc: 'Saiba mais sobre o quadrinho e este site',
        discordButton: 'Discord',
        discordButtonDesc: 'Junte-se à comunidade de fãs de Twokinds no Discord'
    },

    pl: {
        firstPageButton: 'Pierwsza',
        lastPageButton: 'Ostatnia',
        nextPageButton: 'Następna',
        previousPageButton: 'Poprzednia',
        toolsButton: 'Narzędzia',
        pageInput: 'Numer strony',
        goToPageButton: 'Idź do',
        downloadButton: 'Pobierz',
        sketchVerButton: 'Szkic',
        sketchVerButtonAlt: 'Powrót',
        originalSizeOption: 'Oryginalny',
        pageOptionsTitle: 'Opcje strony',
        findPageTitle: 'Znajdź stronę',
        removePageGlowButton: 'Wyłącz podświetlenie strony',
        removePageGlowButtonAlt: 'Włącz podświetlenie strony',
        license: 'TWOKINDS, jego logo i wszystkie powiązane postacie są chronione prawem autorskim © 2024 Thomas J. Fischbach. Wszelkie prawa zastrzeżone.',
        pageViewerButton: 'Przeglądarka stron',
        pageViewerButtonDesc: 'Kontynuuj czytanie: Strona ',
        archiveButton: 'Archiwum',
        archiveButtonDesc: 'Przeglądaj archiwum stron komiksów',
        galleryButton: 'Galeria',
        galleryButtonDesc: 'Przeglądaj wszystkie dzieła związane z Twokinds',
        wikiButton: 'Wiki',
        wikiButtonDesc: 'Zanurz się w świecie Twokinds za pomocą wiki społeczności',
        aboutButton: 'O nas',
        aboutButtonDesc: 'Dowiedz się więcej o komiksie i tej stronie',
        discordButton: 'Discord',
        discordButtonDesc: 'Dołącz do społeczności fanów Twokinds na Discordzie',
        disableSwipesButton: "Wyłącz gesty",
        disableSwipesButtonAlt: "Włącz gesty",
        disableMarginsButton: "Wyłącz marginesy",
        disableMarginsButtonAlt: "Włącz marginesy"
    },

    cs: {
        firstPageButton: 'První',
        lastPageButton: 'Poslední',
        nextPageButton: 'Další',
        previousPageButton: 'Předchozí',
        toolsButton: 'Nástroje',
        pageInput: 'Číslo stránky',
        goToPageButton: 'Přejít na',
        downloadButton: 'Stáhnout',
        sketchVerButton: 'Náčrt',
        sketchVerButtonAlt: 'Zpět',
        originalSizeOption: 'Původní',
        pageOptionsTitle: 'Možnosti stránky',
        findPageTitle: 'Najít stránku',
        removePageGlowButton: 'Vypnout záři stránky',
        removePageGlowButtonAlt: 'Zapnout záři stránky',
        license: 'TWOKINDS, jeho logo a všechny související postavy jsou chráněny autorským právem © 2024 Thomas J. Fischbach. Všechna práva vyhrazena.',
        pageViewerButton: 'Prohlížeč stránek',
        pageViewerButtonDesc: 'Pokračovat ve čtení: Stránka ',
        archiveButton: 'Archiv',
        archiveButtonDesc: 'Procházejte archiv stránek komiksů',
        galleryButton: 'Galerie',
        galleryButtonDesc: 'Prozkoumejte všechna díla související s Twokinds',
        wikiButton: 'Wiki',
        wikiButtonDesc: 'Ponořte se do vesmíru Twokinds pomocí komunitního wiki',
        aboutButton: 'O nás',
        aboutButtonDesc: 'Zjistěte více o komiksu a této stránce',
        discordButton: 'Discord',
        discordButtonDesc: 'Připojte se ke komunitě fanoušků Twokinds na Discordu',
        disableSwipesButton: "Vypnout gesta",
        disableSwipesButtonAlt: "Zapnout gesta",
        disableMarginsButton: "Vypnout okraje",
        disableMarginsButtonAlt: "Zapnout okraje"
    }    
};
