const texts = {
    en: {
        firstPageButton: 'First',
        lastPageButton: 'Last',
        nextPageButton: 'Next',
        previousPageButton: 'Previous',
        toolsButton: 'Tools',
        pageInput: 'Page number',
        goToPageButton: 'Go to',
        downloadButton: 'Download',
        sketchVerButton: 'Sketch',
        sketchVerButtonAlt: 'Return',
        originalSizeOption: 'Original',
        pageOptionsTitle: 'Page options',
        findPageTitle: 'Find page',
        removePageGlowButton: 'Disable page glow',
        removePageGlowButtonAlt: 'Enable page glow',
        license: 'TWOKINDS, its logo, and all related characters are copyright © 2024 Thomas J. Fischbach. All rights reserved.',
        pageViewerButton: 'Page viewer',
        pageViewerButtonDesc: '',
        archiveButton: 'Archive',
        archiveButtonDesc: '',
        galleryButton: 'Gallery',
        galleryButtonDesc: '',
        wikiButton: 'Wiki',
        wikiButtonDesc: '',
        aboutButton: 'About',
        aboutButtonDesc: '',
        discordButton: 'Discord',
        discordButtonDesc: '',
    },
    
    ru: {
        firstPageButton: 'Первая',
        lastPageButton: 'Последняя',
        nextPageButton: 'Следующая',
        previousPageButton: 'Предыдущая',
        toolsButton: 'Инструменты',
        pageInput: 'Номер страницы',
        goToPageButton: 'Перейти',
        downloadButton: 'Скачать',
        sketchVerButton: 'Эскиз',
        sketchVerButtonAlt: 'Вернуться',
        originalSizeOption: 'Оригинал',
        pageOptionsTitle: 'Настройки страницы',
        findPageTitle: 'Найти страницу',
        removePageGlowButton: 'Отключить подсветку страницы',
        removePageGlowButtonAlt: 'Включить подсветку страницы'
    },
    
    be: {
        firstPageButton: 'Першая',
        lastPageButton: 'Апошняя',
        nextPageButton: 'Наступная',
        previousPageButton: 'Папярэдняя',
        toolsButton: 'Інструменты',
        pageInput: 'Нумар старонкі',
        goToPageButton: 'Перайсці',
        downloadButton: 'Спампаваць',
        sketchVerButton: 'Эскіз',
        sketchVerButtonAlt: 'Вярнуцца',
        originalSizeOption: 'Арыгінал',
        pageOptionsTitle: "Опцыі старонкі",
        findPageTitle: "Знайсці старонку",
        removePageGlowButton: 'Адключыць падсвятленне старонкі',
        removePageGlowButtonAlt: 'Уключыць падсвятленне старонкі'
    },

    it: {
        firstPageButton: 'Prima',
        lastPageButton: 'Ultima',
        nextPageButton: 'Successiva',
        previousPageButton: 'Precedente',
        toolsButton: 'Strumenti',
        pageInput: 'Numero di pagina',
        goToPageButton: 'Vai a',
        downloadButton: 'Scarica',
        sketchVerButton: 'Schizzo',
        sketchVerButtonAlt: 'Ritorna',
        originalSizeOption: 'Originale',
        pageOptionsTitle: 'Opzioni di pagina',
        findPageTitle: 'Trova pagina',
        removePageGlowButton: 'Disattiva bagliore pagina',
        removePageGlowButtonAlt: 'Attiva bagliore pagina'
    },
    
    fr: {
        firstPageButton: 'Première',
        lastPageButton: 'Dernière',
        nextPageButton: 'Suivante',
        previousPageButton: 'Précédente',
        toolsButton: 'Outils',
        pageInput: 'Numéro de page',
        goToPageButton: 'Aller à',
        downloadButton: 'Télécharger',
        sketchVerButton: 'Esquisse',
        sketchVerButtonAlt: 'Retour',
        originalSizeOption: 'Original',
        pageOptionsTitle: 'Options de page',
        findPageTitle: 'Trouver page',
        removePageGlowButton: 'Désactiver la lueur de la page',
        removePageGlowButtonAlt: 'Activer la lueur de la page'
    },
    
    es: {
        firstPageButton: 'Primera',
        lastPageButton: 'Última',
        nextPageButton: 'Siguiente',
        previousPageButton: 'Anterior',
        toolsButton: 'Herramientas',
        pageInput: 'Número de página',
        goToPageButton: 'Ir a',
        downloadButton: 'Descargar',
        sketchVerButton: 'Bosquejo',
        sketchVerButtonAlt: 'Regresar',
        originalSizeOption: 'Original',
        pageOptionsTitle: 'Opciones de página',
        findPageTitle: 'Encontrar página',
        removePageGlowButton: 'Desactivar brillo de la página',
        removePageGlowButtonAlt: 'Activar brillo de la página'
    },
    
    de: {
        firstPageButton: 'Erste',
        lastPageButton: 'Letzte',
        nextPageButton: 'Nächste',
        previousPageButton: 'Vorherige',
        toolsButton: 'Werkzeuge',
        pageInput: 'Seitenzahl',
        goToPageButton: 'Gehe zu',
        downloadButton: 'Herunterladen',
        sketchVerButton: 'Skizze',
        sketchVerButtonAlt: 'Zurück',
        originalSizeOption: 'Original',
        pageOptionsTitle: 'Seitenoptionen',
        findPageTitle: 'Seite finden',
        removePageGlowButton: 'Seitenleuchten deaktivieren',
        removePageGlowButtonAlt: 'Seitenleuchten aktivieren'
    },

    pt: {
        firstPageButton: 'Primeira',
        lastPageButton: 'Última',
        nextPageButton: 'Próxima',
        previousPageButton: 'Anterior',
        toolsButton: 'Ferramentas',
        pageInput: 'Número da página',
        goToPageButton: 'Ir para',
        downloadButton: 'Baixar',
        sketchVerButton: 'Esboço',
        sketchVerButtonAlt: 'Voltar',
        originalSizeOption: 'Original',
        pageOptionsTitle: 'Opções de página',
        findPageTitle: 'Encontrar página',
        removePageGlowButton: 'Desativar brilho da página',
        removePageGlowButtonAlt: 'Ativar brilho da página'
    },

    pl: {
        firstPageButton: 'Pierwsza',
        lastPageButton: 'Ostatnia',
        nextPageButton: 'Następna',
        previousPageButton: 'Poprzednia',
        toolsButton: 'Narzędzia',
        pageInput: 'Numer strony',
        goToPageButton: 'Idź do',
        downloadButton: 'Pobierz',
        sketchVerButton: 'Szkic',
        sketchVerButtonAlt: 'Powrót',
        originalSizeOption: 'Oryginalny',
        pageOptionsTitle: 'Opcje strony',
        findPageTitle: 'Znajdź stronę',
        removePageGlowButton: 'Wyłącz podświetlenie strony',
        removePageGlowButtonAlt: 'Włącz podświetlenie strony'
    },

    cs: {
        firstPageButton: 'První',
        lastPageButton: 'Poslední',
        nextPageButton: 'Další',
        previousPageButton: 'Předchozí',
        toolsButton: 'Nástroje',
        pageInput: 'Číslo stránky',
        goToPageButton: 'Přejít na',
        downloadButton: 'Stáhnout',
        sketchVerButton: 'Náčrt',
        sketchVerButtonAlt: 'Zpět',
        originalSizeOption: 'Původní',
        pageOptionsTitle: 'Možnosti stránky',
        findPageTitle: 'Najít stránku',
        removePageGlowButton: 'Vypnout záři stránky',
        removePageGlowButtonAlt: 'Zapnout záři stránky'
    }    
};
