const texts = {
    en: {
        title: "Server Rules",
        rule1: "1. Follow Discord's Guidelines.",
        rule1_details: "These guidelines are applicable everywhere on Discord. Review them here if needed: <a href='https://discord.com/guidelines' class='btn'>Discord Guidelines</a>",
        rule2: "2. Be respectful towards fellow members.",
        rule2_details_1: "Enjoy the content and time together, avoiding offensive behavior or bigotry based on race, identity, religion, etc.",
        rule2_details_2: "Playful jabs are fine, but use common sense and respect boundaries, especially with members you aren't close friends with.",
        rule3: "3. Respect the staff.",
        rule3_details_1: "The staff members are part of the community and are working to maintain a welcoming environment.",
        rule3_details_2: "Help them by not acting foolishly and making their job easier.",
        rule4: "4. Do not:",
        rule4_details_1: "Advertise other Discord servers without admin approval. We are not interested in joining or promoting unrelated servers like 'Pawsome Fun House UwU'.",
        rule4_details_2: "Engage in roleplay. Using Twokinds characters as your name or profile picture is considered roleplay. We are not interested in having 128 Floras. One-time actions like hugs or high fives are not considered roleplay.",
        rule4_details_3: "Use alternate accounts.",
        rule4_details_4: "Use a name or nickname that cannot be pinged. We need a way to address you!",
        rule4_details_5: "Post inappropriate content, especially in <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a>. Examples include earrape, NSFW content (pornographic material is not allowed even though this is a furry server), and messages promoting harm or hate towards any group. Use common sense; moderators have the authority to remove messages that fall into this category.",
        rule5: "5. Ankles must be covered at all times.",
        rule5_details: "As per Basitin Law, J.A., 389, c. E-62, s. 1.",
        rule6: "6. Use appropriate channels for conversation.",
        rule7: "7. Art channel rules:",
        rule7_details: "Refer to <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a>",
        rule8: "8. Understand our discipline system:",
        rule8_warnings: "Warnings: Warnings are not strikes; consider them a gentle reminder. Accumulating warnings will result in strikes.",
        rule8_strikes: "Strikes:",
        strike_details_1: "First strike (5 warnings) | Consequence: 12 hours in the dungeon",
        strike_details_2: "Second strike (+3 warnings) | Consequence: 24 hours in the dungeon with limited server access after release.",
        strike_details_3: "Third strike (+2 warnings) | Consequence: Ban, which may be permanent or temporary depending on the severity of the actions.",
    },
    ru: {
        title: "Правила сервера",
        rule1: "1. Соблюдайте правила Discord.",
        rule1_details: "Эти правила применимы везде на Discord. Ознакомьтесь с ними здесь, если необходимо: <a href='https://discord.com/guidelines' class='btn'>Правила Discord</a>",
        rule2: "2. Будьте уважительны к другим участникам.",
        rule2_details_1: "Наслаждайтесь контентом и временем вместе, избегайте оскорбительного поведения или предвзятости по признаку расы, идентичности, религии и т.д.",
        rule2_details_2: "Шутки допустимы, но используйте здравый смысл и уважайте границы, особенно с теми, кого вы не знаете близко.",
        rule3: "3. Уважайте администрацию.",
        rule3_details_1: "Администрация является частью сообщества и работает над тем, чтобы поддерживать доброжелательную атмосферу.",
        rule3_details_2: "Помогайте им, не ведите себя глупо и облегчайте их работу.",
        rule4: "4. Запрещено:",
        rule4_details_1: "Рекламировать другие серверы Discord без разрешения администрации. Нам не интересно присоединяться или продвигать нерелевантные серверы вроде 'Pawsome Fun House UwU'.",
        rule4_details_2: "Участвовать в ролевых играх. Использование персонажей Twokinds в качестве имени или аватара считается ролевой игрой. Нам не нужно 128 Флор. Одноразовые действия, такие как объятия или хай-файвы, не считаются ролевой игрой.",
        rule4_details_3: "Использовать альтернативные аккаунты.",
        rule4_details_4: "Использовать имя или никнейм, который нельзя упомянуть с помощью пинга. Нам нужно иметь возможность вас вызвать!",
        rule4_details_5: "Публиковать неподобающий контент, особенно в <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a>. Примеры включают earrape, NSFW контент (порнографические материалы запрещены, даже если это фурри-сервер) и сообщения, пропагандирующие вред или ненависть к какой-либо группе. Используйте здравый смысл; модераторы имеют право удалять сообщения, попадающие в эту категорию.",
        rule5: "5. Лодыжки должны быть покрыты в любое время.",
        rule5_details: "Согласно Баситинскому Закону, J.A., 389, c. E-62, s. 1.",
        rule6: "6. Используйте подходящие каналы для общения.",
        rule7: "7. Правила канала для искусства:",
        rule7_details: "Обратитесь к <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a>",
        rule8: "8. Понимайте нашу систему дисциплины:",
        rule8_warnings: "Предупреждения: Предупреждения не являются страйками; считайте их мягким напоминанием. Накопление предупреждений приведет к страйкам.",
        rule8_strikes: "Страйки:",
        strike_details_1: "Первый страйк (5 предупреждений) | Наказание: 12 часов в подземелье",
        strike_details_2: "Второй страйк (+3 предупреждения) | Наказание: 24 часа в подземелье с ограниченным доступом к серверу после выхода.",
        strike_details_3: "Третий страйк (+2 предупреждения) | Наказание: Бан, который может быть постоянным или временным в зависимости от тяжести действий.",
    },
    fr: {
        title: "Règles du serveur",
        rule1: "1. Respectez les règles de Discord.",
        rule1_details: "Ces règles s'appliquent partout sur Discord. Consultez-les ici si nécessaire : <a href='https://discord.com/guidelines' class='btn'>Règles de Discord</a>",
        rule2: "2. Soyez respectueux envers les autres membres.",
        rule2_details_1: "Profitez du contenu et du temps ensemble, en évitant tout comportement offensant ou discriminatoire basé sur la race, l'identité, la religion, etc.",
        rule2_details_2: "Les petites taquineries sont acceptées, mais faites preuve de bon sens et respectez les limites, surtout avec les membres que vous ne connaissez pas bien.",
        rule3: "3. Respectez l'administration.",
        rule3_details_1: "Les membres de l'administration font partie de la communauté et travaillent pour maintenir un environnement accueillant.",
        rule3_details_2: "Aidez-les en évitant de vous comporter de manière irresponsable et facilitez-leur la tâche.",
        rule4: "4. Il est interdit de :",
        rule4_details_1: "Faire de la publicité pour d'autres serveurs Discord sans l'approbation de l'administration. Nous ne sommes pas intéressés par rejoindre ou promouvoir des serveurs non liés comme 'Pawsome Fun House UwU'.",
        rule4_details_2: "Participer à des jeux de rôle. Utiliser des personnages de Twokinds comme nom ou image de profil est considéré comme un jeu de rôle. Nous n'avons pas besoin de 128 Flora. Les actions ponctuelles comme des câlins ou des high fives ne sont pas considérées comme du jeu de rôle.",
        rule4_details_3: "Utiliser des comptes alternatifs.",
        rule4_details_4: "Utiliser un nom ou pseudonyme qui ne peut pas être mentionné par un ping. Nous avons besoin d'un moyen de vous identifier !",
        rule4_details_5: "Poster du contenu inapproprié, en particulier dans <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a>. Les exemples incluent earrape, du contenu NSFW (les contenus pornographiques sont interdits même si c'est un serveur furry) et des messages incitant à la haine ou à la violence contre un groupe. Faites preuve de bon sens ; les modérateurs ont le droit de supprimer les messages qui tombent dans cette catégorie.",
        rule5: "5. Les chevilles doivent toujours être couvertes.",
        rule5_details: "Conformément à la loi Basitin, J.A., 389, c. E-62, s. 1.",
        rule6: "6. Utilisez les canaux appropriés pour vos discussions.",
        rule7: "7. Règles du canal d'art :",
        rule7_details: "Référez-vous à <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a>",
        rule8: "8. Comprenez notre système disciplinaire :",
        rule8_warnings: "Avertissements : Les avertissements ne sont pas des strikes ; considérez-les comme un rappel gentil. Accumuler des avertissements entraînera des strikes.",
        rule8_strikes: "Strikes :",
        strike_details_1: "Premier strike (5 avertissements) | Conséquence : 12 heures dans le donjon",
        strike_details_2: "Deuxième strike (+3 avertissements) | Conséquence : 24 heures dans le donjon avec un accès limité au serveur après la libération.",
        strike_details_3: "Troisième strike (+2 avertissements) | Conséquence : Bannissement, qui peut être permanent ou temporaire selon la gravité des actions.",
    },
    de: {
        title: "Serverregeln",
        rule1: "1. Befolgt die Richtlinien von Discord.",
        rule1_details: "Diese Richtlinien gelten überall auf Discord. Überprüft sie hier, wenn nötig: <a href='https://discord.com/guidelines' class='btn'>Discord-Richtlinien</a>",
        rule2: "2. Seid respektvoll gegenüber anderen Mitgliedern.",
        rule2_details_1: "Genießt die Inhalte und die gemeinsame Zeit, vermeidet beleidigendes Verhalten oder Vorurteile aufgrund von Rasse, Identität, Religion usw.",
        rule2_details_2: "Kleine Sticheleien sind in Ordnung, aber nutzt gesunden Menschenverstand und respektiert die Grenzen, insbesondere bei Mitgliedern, mit denen ihr nicht eng befreundet seid.",
        rule3: "3. Respektiert die Administration.",
        rule3_details_1: "Die Mitglieder der Administration sind Teil der Gemeinschaft und arbeiten daran, ein einladendes Umfeld zu schaffen.",
        rule3_details_2: "Helft ihnen, indem ihr euch nicht dumm verhaltet und ihnen die Arbeit erleichtert.",
        rule4: "4. Folgendes ist verboten:",
        rule4_details_1: "Andere Discord-Server ohne Zustimmung der Admins zu bewerben. Wir sind nicht daran interessiert, uns anderen, nicht verwandten Servern wie 'Pawsome Fun House UwU' anzuschließen oder sie zu fördern.",
        rule4_details_2: "Rollenspiele zu betreiben. Die Verwendung von Twokinds-Charakteren als Name oder Profilbild wird als Rollenspiel angesehen. Wir brauchen keine 128 Floras. Einmalige Aktionen wie Umarmungen oder High-Fives gelten nicht als Rollenspiel.",
        rule4_details_3: "Alternative Accounts zu verwenden.",
        rule4_details_4: "Einen Namen oder Spitznamen zu verwenden, der nicht gepingt werden kann. Wir müssen euch ansprechen können!",
        rule4_details_5: "Unangemessene Inhalte zu posten, insbesondere in <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a>. Beispiele sind earrape, NSFW-Inhalte (pornografisches Material ist nicht erlaubt, auch wenn dies ein Furry-Server ist) und Nachrichten, die Hass oder Schaden gegenüber einer Gruppe fördern. Nutzt gesunden Menschenverstand; die Moderatoren haben das Recht, Nachrichten zu entfernen, die in diese Kategorie fallen.",
        rule5: "5. Die Knöchel müssen jederzeit bedeckt sein.",
        rule5_details: "Nach Basitin-Recht, J.A., 389, c. E-62, s. 1.",
        rule6: "6. Verwendet die passenden Kanäle für Gespräche.",
        rule7: "7. Regeln für den Kunstkanal:",
        rule7_details: "Siehe <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a>",
        rule8: "8. Versteht unser Disziplinarsystem:",
        rule8_warnings: "Warnungen: Warnungen sind keine Strikes; betrachtet sie als sanfte Erinnerung. Das Ansammeln von Warnungen führt zu Strikes.",
        rule8_strikes: "Strikes:",
        strike_details_1: "Erster Strike (5 Warnungen) | Konsequenz: 12 Stunden im Kerker",
        strike_details_2: "Zweiter Strike (+3 Warnungen) | Konsequenz: 24 Stunden im Kerker mit eingeschränktem Serverzugang nach der Entlassung.",
        strike_details_3: "Dritter Strike (+2 Warnungen) | Konsequenz: Bann, der je nach Schwere der Handlung dauerhaft oder vorübergehend sein kann.",
    },
    pl: {
        title: "Zasady serwera",
        rule1: "1. Przestrzegaj zasad Discorda.",
        rule1_details: "Te zasady obowiązują wszędzie na Discordzie. Przejrzyj je tutaj, jeśli potrzebujesz: <a href='https://discord.com/guidelines' class='btn'>Zasady Discorda</a>",
        rule2: "2. Bądź szanujący wobec innych członków.",
        rule2_details_1: "Ciesz się treściami i wspólnym czasem, unikając obraźliwego zachowania lub uprzedzeń na podstawie rasy, tożsamości, religii itp.",
        rule2_details_2: "Drobne żarty są w porządku, ale używaj zdrowego rozsądku i szanuj granice, zwłaszcza w stosunku do członków, z którymi nie jesteś blisko związany.",
        rule3: "3. Szanuj administrację.",
        rule3_details_1: "Członkowie administracji są częścią społeczności i pracują nad utrzymaniem przyjaznego środowiska.",
        rule3_details_2: "Pomóż im, nie zachowując się głupio i ułatwiając im pracę.",
        rule4: "4. Nie wolno:",
        rule4_details_1: "Reklamować innych serwerów Discord bez zgody administracji. Nie jesteśmy zainteresowani dołączaniem do lub promowaniem niepowiązanych serwerów, takich jak 'Pawsome Fun House UwU'.",
        rule4_details_2: "Uczestniczyć w odgrywaniu ról. Używanie postaci z Twokinds jako swojego imienia lub zdjęcia profilowego jest uważane za odgrywanie ról. Nie chcemy 128 Flor. Jednorazowe akcje, takie jak przytulanie lub przybijanie piątek, nie są uważane za odgrywanie ról.",
        rule4_details_3: "Używać alternatywnych kont.",
        rule4_details_4: "Używać imienia lub pseudonimu, którego nie można zpingować. Potrzebujemy sposobu, aby się do ciebie zwrócić!",
        rule4_details_5: "Publikować nieodpowiednie treści, szczególnie w <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a>. Przykłady obejmują earrape, treści NSFW (materiały pornograficzne są zabronione, mimo że jest to serwer furry) oraz wiadomości promujące nienawiść lub szkodę wobec jakiejkolwiek grupy. Używaj zdrowego rozsądku; moderatorzy mają prawo usunąć wiadomości, które należą do tej kategorii.",
        rule5: "5. Kostki muszą być zakryte przez cały czas.",
        rule5_details: "Zgodnie z prawem Basitin, J.A., 389, c. E-62, s. 1.",
        rule6: "6. Używaj odpowiednich kanałów do rozmów.",
        rule7: "7. Zasady kanału sztuki:",
        rule7_details: "Zobacz <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a>",
        rule8: "8. Zrozum nasz system dyscyplinarny:",
        rule8_warnings: "Ostrzeżenia: Ostrzeżenia to nie strajki; traktuj je jako delikatne przypomnienie. Nagromadzenie ostrzeżeń skutkuje strajkami.",
        rule8_strikes: "Strajki:",
        strike_details_1: "Pierwszy strajk (5 ostrzeżeń) | Konsekwencja: 12 godzin w lochu",
        strike_details_2: "Drugi strajk (+3 ostrzeżenia) | Konsekwencja: 24 godziny w lochu z ograniczonym dostępem do serwera po uwolnieniu.",
        strike_details_3: "Trzeci strajk (+2 ostrzeżenia) | Konsekwencja: Ban, który może być trwały lub tymczasowy, w zależności od powagi działań.",
    },
    es: {
        title: "Reglas del servidor",
        rule1: "1. Sigue las normas de Discord.",
        rule1_details: "Estas reglas se aplican en todo Discord. Revíselas aquí si lo necesitas: <a href='https://discord.com/guidelines' class='btn'>Normas de Discord</a>",
        rule2: "2. Sé respetuoso con los demás miembros.",
        rule2_details_1: "Disfruta del contenido y del tiempo juntos, evitando comportamientos ofensivos o prejuicios basados en raza, identidad, religión, etc.",
        rule2_details_2: "Bromas ligeras están bien, pero usa el sentido común y respeta los límites, especialmente con miembros con los que no tienes mucha confianza.",
        rule3: "3. Respeta al personal.",
        rule3_details_1: "Los miembros del staff son parte de la comunidad y trabajan para mantener un ambiente acogedor.",
        rule3_details_2: "Ayúdales no haciendo tonterías y facilitándoles su trabajo.",
        rule4: "4. No hagas lo siguiente:",
        rule4_details_1: "No hagas publicidad de otros servidores de Discord sin la aprobación de un administrador. No estamos interesados en unirnos o promover servidores no relacionados como 'Pawsome Fun House UwU'.",
        rule4_details_2: "No hagas rol. Usar personajes de Twokinds como tu nombre o foto de perfil se considera rol. No queremos 128 Floras. Acciones puntuales como abrazos o choques de manos no se consideran rol.",
        rule4_details_3: "No uses cuentas alternativas.",
        rule4_details_4: "No uses un nombre o apodo que no se pueda mencionar. ¡Necesitamos una forma de dirigirnos a ti!",
        rule4_details_5: "No publiques contenido inapropiado, especialmente en <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a>. Ejemplos incluyen earrape, contenido NSFW (el material pornográfico no está permitido, aunque sea un servidor furry), y mensajes que promuevan el odio o daño hacia cualquier grupo. Usa el sentido común; los moderadores tienen la autoridad para eliminar mensajes que entren en esta categoría.",
        rule5: "5. Los tobillos deben estar cubiertos en todo momento.",
        rule5_details: "Según la ley de los Basitin, J.A., 389, c. E-62, s. 1.",
        rule6: "6. Usa los canales adecuados para las conversaciones.",
        rule7: "7. Reglas del canal de arte:",
        rule7_details: "Consulta <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a>",
        rule8: "8. Entiende nuestro sistema de disciplina:",
        rule8_warnings: "Advertencias: Las advertencias no son strikes; considérelas recordatorios suaves. Acumular advertencias resultará en strikes.",
        rule8_strikes: "Strikes:",
        strike_details_1: "Primer strike (5 advertencias) | Consecuencia: 12 horas en el calabozo",
        strike_details_2: "Segundo strike (+3 advertencias) | Consecuencia: 24 horas en el calabozo con acceso limitado al servidor tras la liberación.",
        strike_details_3: "Tercer strike (+2 advertencias) | Consecuencia: Expulsión, que puede ser permanente o temporal dependiendo de la gravedad de las acciones.",
    },
    it: {
        title: "Regole del server",
        rule1: "1. Rispetta le Linee Guida di Discord.",
        rule1_details: "Queste regole valgono ovunque su Discord. Controllale qui se necessario: <a href='https://discord.com/guidelines' class='btn'>Linee Guida di Discord</a>",
        rule2: "2. Sii rispettoso con gli altri membri.",
        rule2_details_1: "Goditi i contenuti e il tempo insieme, evitando comportamenti offensivi o pregiudizi basati su razza, identità, religione, ecc.",
        rule2_details_2: "Le battute leggere vanno bene, ma usa il buon senso e rispetta i confini, soprattutto con i membri con cui non hai molta confidenza.",
        rule3: "3. Rispetta il personale.",
        rule3_details_1: "I membri del personale sono parte della comunità e lavorano per mantenere un ambiente accogliente.",
        rule3_details_2: "Aiutali a non rendere il loro lavoro più difficile comportandoti in modo appropriato.",
        rule4: "4. Non fare quanto segue:",
        rule4_details_1: "Non fare pubblicità ad altri server di Discord senza approvazione dell’amministratore. Non siamo interessati a unirci o promuovere server non correlati come 'Pawsome Fun House UwU'.",
        rule4_details_2: "Non fare roleplay. Usare i personaggi di Twokinds come nome o immagine del profilo è considerato roleplay. Non abbiamo bisogno di 128 Floras. Azioni occasionali come abbracci o alti cinque non sono considerate roleplay.",
        rule4_details_3: "Non usare account alternativi.",
        rule4_details_4: "Non usare un nome o soprannome che non può essere taggato. Abbiamo bisogno di un modo per rivolgerti!",
        rule4_details_5: "Non postare contenuti inappropriati, specialmente in <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a>. Esempi includono earrape, contenuti NSFW (il materiale pornografico non è permesso, anche se questo è un server furry), e messaggi che promuovono odio o danno verso qualsiasi gruppo. Usa il buon senso; i moderatori hanno l’autorità di rimuovere i messaggi che rientrano in questa categoria.",
        rule5: "5. Le caviglie devono essere coperte in ogni momento.",
        rule5_details: "Secondo la legge Basitin, J.A., 389, c. E-62, s. 1.",
        rule6: "6. Usa i canali appropriati per le conversazioni.",
        rule7: "7. Regole del canale arte:",
        rule7_details: "Consulta <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a>",
        rule8: "8. Comprendi il nostro sistema disciplinare:",
        rule8_warnings: "Avvertenze: Le avvertenze non sono sanzioni; considerale come promemoria gentili. Accumulare avvertenze porterà a sanzioni.",
        rule8_strikes: "Sanzioni:",
        strike_details_1: "Prima sanzione (5 avvertenze) | Conseguenza: 12 ore in prigione",
        strike_details_2: "Seconda sanzione (+3 avvertenze) | Conseguenza: 24 ore in prigione con accesso limitato al server dopo la liberazione.",
        strike_details_3: "Terza sanzione (+2 avvertenze) | Conseguenza: Bannamento, che può essere permanente o temporaneo a seconda della gravità delle azioni.",
    },
    uk: {
        title: "Правила сервера",
        rule1: "1. Дотримуйтесь правил Discord.",
        rule1_details: "Ці правила застосовуються на всьому Discord. Перегляньте їх тут, якщо потрібно: <a href='https://discord.com/guidelines' class='btn'>Правила Discord</a>",
        rule2: "2. Будьте ввічливими до інших учасників.",
        rule2_details_1: "Насолоджуйтесь контентом і часом разом, уникаючи образливих поведінкових дій або упереджень на основі раси, ідентичності, релігії тощо.",
        rule2_details_2: "Легкі жарти допустимі, але використовуйте здоровий глузд і поважайте межі, особливо з тими, з ким ви не близькі друзі.",
        rule3: "3. Поважайте адміністрацію.",
        rule3_details_1: "Члени адміністрації є частиною спільноти і працюють над створенням дружньої атмосфери.",
        rule3_details_2: "Допоможіть їм, не ведучи себе нерозумно та полегшуючи їм роботу.",
        rule4: "4. Не робіть наступного:",
        rule4_details_1: "Не рекламуйте інші сервери Discord без дозволу адміністратора. Ми не зацікавлені у приєднанні до або просуванні непов’язаних серверів, таких як 'Pawsome Fun House UwU'.",
        rule4_details_2: "Не беріть участі в рольових іграх. Використання персонажів Twokinds як вашого імені чи зображення профілю вважається рольовою грою. Нам не потрібно 128 Флор. Одноразові дії, такі як обійми або п’ятихатки, не вважаються рольовими іграми.",
        rule4_details_3: "Не використовуйте альтернативні акаунти.",
        rule4_details_4: "Не використовуйте ім’я або псевдонім, який не можна відзначити. Нам потрібно мати можливість звертатися до вас!",
        rule4_details_5: "Не публікуйте неприпустимий контент, особливо в <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a>. Приклади включають earrape, контент NSFW (порнографічні матеріали не дозволені, навіть якщо це furry сервер), і повідомлення, які пропагують ненависть або шкоду будь-якій групі. Використовуйте здоровий глузд; модератори мають право видаляти повідомлення, які потрапляють під цю категорію.",
        rule5: "5. Щиколотки повинні бути закриті в будь-який час.",
        rule5_details: "Згідно з законом Basitin, J.A., 389, c. E-62, s. 1.",
        rule6: "6. Використовуйте відповідні канали для спілкування.",
        rule7: "7. Правила каналу мистецтв:",
        rule7_details: "Дивіться <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a>",
        rule8: "8. Розумійте нашу систему дисципліни:",
        rule8_warnings: "Попередження: Попередження не є страйками; вважайте їх м’якими нагадуваннями. Накопичення попереджень призведе до страйків.",
        rule8_strikes: "Страйки:",
        strike_details_1: "Перший страйк (5 попереджень) | Наслідок: 12 годин у в’язниці",
        strike_details_2: "Другий страйк (+3 попередження) | Наслідок: 24 години у в’язниці з обмеженим доступом до сервера після виходу.",
        strike_details_3: "Третій страйк (+2 попередження) | Наслідок: Бан, який може бути постійним або тимчасовим залежно від серйозності дій.",
    },
    pt: {
        title: "Regras do servidor",
        rule1: "1. Siga as Diretrizes do Discord.",
        rule1_details: "Essas regras se aplicam em todo o Discord. Revise-as aqui se necessário: <a href='https://discord.com/guidelines' class='btn'>Diretrizes do Discord</a>",
        rule2: "2. Seja respeitoso com os outros membros.",
        rule2_details_1: "Aproveite o conteúdo e o tempo juntos, evitando comportamentos ofensivos ou preconceituosos baseados em raça, identidade, religião, etc.",
        rule2_details_2: "Zombarias leves são aceitáveis, mas use o bom senso e respeite os limites, especialmente com membros com os quais você não tem muita amizade.",
        rule3: "3. Respeite a equipe.",
        rule3_details_1: "Os membros da equipe são parte da comunidade e trabalham para manter um ambiente acolhedor.",
        rule3_details_2: "Ajude-os não agindo de forma tola e facilitando seu trabalho.",
        rule4: "4. Não faça o seguinte:",
        rule4_details_1: "Não faça propaganda de outros servidores do Discord sem a aprovação do administrador. Não estamos interessados em nos juntar ou promover servidores não relacionados, como 'Pawsome Fun House UwU'.",
        rule4_details_2: "Não participe de roleplay. Usar personagens de Twokinds como seu nome ou foto de perfil é considerado roleplay. Não queremos 128 Floras. Ações pontuais como abraços ou cumprimentos não são consideradas roleplay.",
        rule4_details_3: "Não use contas alternativas.",
        rule4_details_4: "Não use um nome ou apelido que não possa ser marcado. Precisamos de uma forma de nos referirmos a você!",
        rule4_details_5: "Não publique conteúdo inapropriado, especialmente em <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a>. Exemplos incluem earrape, conteúdo NSFW (material pornográfico não é permitido, mesmo sendo um servidor furry), e mensagens que promovem ódio ou dano a qualquer grupo. Use o bom senso; os moderadores têm a autoridade para remover mensagens que se enquadrem nesta categoria.",
        rule5: "5. Os tornozelos devem estar cobertos o tempo todo.",
        rule5_details: "De acordo com a Lei Basitin, J.A., 389, c. E-62, s. 1.",
        rule6: "6. Use os canais apropriados para conversas.",
        rule7: "7. Regras do canal de arte:",
        rule7_details: "Consulte <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a>",
        rule8: "8. Entenda nosso sistema de disciplina:",
        rule8_warnings: "Avisos: Avisos não são sanções; considere-os lembretes gentis. Acumular avisos resultará em sanções.",
        rule8_strikes: "Sanções:",
        strike_details_1: "Primeira sanção (5 avisos) | Consequência: 12 horas na masmorra",
        strike_details_2: "Segunda sanção (+3 avisos) | Consequência: 24 horas na masmorra com acesso limitado ao servidor após a liberação.",
        strike_details_3: "Terceira sanção (+2 avisos) | Consequência: Banimento, que pode ser permanente ou temporário, dependendo da gravidade das ações.",
    },
    nl: {
        title: "Serverregels",
        rule1: "1. Volg de Richtlijnen van Discord.",
        rule1_details: "Deze richtlijnen zijn overal op Discord van toepassing. Bekijk ze hier indien nodig: <a href='https://discord.com/guidelines' class='btn'>Discord Richtlijnen</a>",
        rule2: "2. Wees respectvol naar andere leden.",
        rule2_details_1: "Geniet van de inhoud en de tijd samen, vermijd beledigend gedrag of vooroordelen op basis van ras, identiteit, religie, enz.",
        rule2_details_2: "Lichte grappen zijn prima, maar gebruik gezond verstand en respecteer grenzen, vooral met leden met wie je niet goed bevriend bent.",
        rule3: "3. Respecteer het personeel.",
        rule3_details_1: "De leden van het personeel maken deel uit van de gemeenschap en werken aan een gastvrije omgeving.",
        rule3_details_2: "Help hen door je niet dom te gedragen en hun werk makkelijker te maken.",
        rule4: "4. Doe het volgende niet:",
        rule4_details_1: "Adverteer geen andere Discord-servers zonder toestemming van de beheerder. We zijn niet geïnteresseerd in het aansluiten bij of promoten van niet-verwante servers zoals 'Pawsome Fun House UwU'.",
        rule4_details_2: "Doe niet aan roleplay. Het gebruik van Twokinds-personages als je naam of profielfoto wordt beschouwd als roleplay. We willen geen 128 Floras. Eenmalige acties zoals knuffels of high-fives worden niet als roleplay beschouwd.",
        rule4_details_3: "Gebruik geen alternatieve accounts.",
        rule4_details_4: "Gebruik geen naam of bijnaam die niet getagd kan worden. We hebben een manier nodig om je aan te spreken!",
        rule4_details_5: "Plaats geen ongepaste inhoud, vooral niet in <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a>. Voorbeelden zijn earrape, NSFW-inhoud (pornografisch materiaal is niet toegestaan, ook al is dit een furry-server), en berichten die haat of schade tegen enige groep bevorderen. Gebruik gezond verstand; moderators hebben de bevoegdheid om berichten te verwijderen die in deze categorie vallen.",
        rule5: "5. Enkels moeten altijd bedekt zijn.",
        rule5_details: "Volgens de Basitin-wet, J.A., 389, c. E-62, s. 1.",
        rule6: "6. Gebruik de juiste kanalen voor gesprekken.",
        rule7: "7. Regels voor het kunstkanaal:",
        rule7_details: "Raadpleeg <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a>",
        rule8: "8. Begrijp ons disciplinaire systeem:",
        rule8_warnings: "Waarschuwingen: Waarschuwingen zijn geen straffen; beschouw ze als vriendelijke herinneringen. Het accumuleren van waarschuwingen zal leiden tot straffen.",
        rule8_strikes: "Strafpunten:",
        strike_details_1: "Eerste strafpunt (5 waarschuwingen) | Gevolg: 12 uur in de kerker",
        strike_details_2: "Tweede strafpunt (+3 waarschuwingen) | Gevolg: 24 uur in de kerker met beperkte toegang tot de server na vrijlating.",
        strike_details_3: "Derde strafpunt (+2 waarschuwingen) | Gevolg: Bannering, die permanent of tijdelijk kan zijn, afhankelijk van de ernst van de acties.",
    },
    tr: {
        title: "Sunucu Kuralları",
        rule1: "1. Discord'un Yönergelerine Uyun.",
        rule1_details: "Bu yönergeler Discord'un her yerinde geçerlidir. Gerekirse burada gözden geçirin: <a href='https://discord.com/guidelines' class='btn'>Discord Yönergeleri</a>",
        rule2: "2. Diğer üyelere saygılı olun.",
        rule2_details_1: "İçeriğin ve zamanın tadını çıkarın, ırk, kimlik, din vb. temelinde hakaret edici davranışlardan veya önyargılardan kaçının.",
        rule2_details_2: "Hafif şakalar sorun olmaz, ancak sağduyu kullanın ve sınırları saygıyla koruyun, özellikle de yakın arkadaş olmadığınız üyelerle.",
        rule3: "3. Personeli saygıyla karşılayın.",
        rule3_details_1: "Personel üyeleri topluluğun bir parçasıdır ve misafirperver bir ortam oluşturmak için çalışmaktadır.",
        rule3_details_2: "Onlara yardımcı olun, aptalca davranmayarak ve işlerini kolaylaştırarak.",
        rule4: "4. Şunları yapmayın:",
        rule4_details_1: "Yönetici onayı olmadan diğer Discord sunucularını tanıtmadan. 'Pawsome Fun House UwU' gibi alakasız sunuculara katılmak veya tanıtmakla ilgilenmiyoruz.",
        rule4_details_2: "Rol yapma etkinliklerinde bulunmayın. Twokinds karakterlerini adınız veya profil resminiz olarak kullanmak rol yapma olarak kabul edilir. 128 Flora'ya ihtiyacımız yok. Tek seferlik hareketler, öpücükler veya yüksek beşler rol yapma olarak kabul edilmez.",
        rule4_details_3: "Alternatif hesaplar kullanmayın.",
        rule4_details_4: "Etiketlenemeyen bir isim veya takma ad kullanmayın. Size hitap edebilmemiz için bir yol ihtiyacımız var!",
        rule4_details_5: "Uygunsuz içerik paylaşmayın, özellikle de <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a> kanalında. Örnekler arasında earrape, NSFW içerik (pornografik materyaller bu sunucuda bile yasaktır) ve herhangi bir gruba zarar veya nefret yayma mesajları bulunur. Sağduyulu olun; moderatörler bu kategoriye giren mesajları kaldırma yetkisine sahiptir.",
        rule5: "5. Ayak bilekleri her zaman kapalı olmalıdır.",
        rule5_details: "Basitin Kanunu, J.A., 389, c. E-62, s. 1'e göre.",
        rule6: "6. Sohbetler için uygun kanalları kullanın.",
        rule7: "7. Sanat kanalı kuralları:",
        rule7_details: "Detaylar için <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a>'ya bakın",
        rule8: "8. Disiplin sistemimizi anlayın:",
        rule8_warnings: "Uyarılar: Uyarılar ceza değildir; bunları nazik hatırlatmalar olarak düşünün. Uyarı birikimi cezalara yol açacaktır.",
        rule8_strikes: "Cezalar:",
        strike_details_1: "Birinci ceza (5 uyarı) | Sonuç: 12 saat zindanda",
        strike_details_2: "İkinci ceza (+3 uyarı) | Sonuç: Serbest bırakıldıktan sonra sunucuya sınırlı erişim ile 24 saat zindanda",
        strike_details_3: "Üçüncü ceza (+2 uyarı) | Sonuç: Davranışların ciddiyetine bağlı olarak kalıcı veya geçici olabilecek yasaklama.",
    },
    ja: {
        title: "サーバーのルール",
        rule1: "1. Discordのガイドラインに従ってください。",
        rule1_details: "これらのガイドラインはDiscord全体で適用されます。必要に応じてこちらで確認してください: <a href='https://discord.com/guidelines' class='btn'>Discord ガイドライン</a>",
        rule2: "2. 他のメンバーに対して敬意を持って接してください。",
        rule2_details_1: "コンテンツと一緒に過ごす時間を楽しみ、民族、アイデンティティ、宗教などに基づく攻撃的な行動や偏見を避けてください。",
        rule2_details_2: "軽い冗談は問題ありませんが、常識を持って行動し、特に親しい友人でないメンバーとの境界を尊重してください。",
        rule3: "3. スタッフを尊重してください。",
        rule3_details_1: "スタッフはコミュニティの一部であり、歓迎する環境を維持するために働いています。",
        rule3_details_2: "無駄な行動をせず、スタッフの仕事を楽にすることで助けてください。",
        rule4: "4. 次のことをしないでください:",
        rule4_details_1: "管理者の承認なしに他のDiscordサーバーを宣伝しないでください。『Pawsome Fun House UwU』のような無関係なサーバーに参加したり、宣伝したりすることには興味がありません。",
        rule4_details_2: "ロールプレイに参加しないでください。Twokindsのキャラクターを名前やプロフィール写真として使用することはロールプレイと見なされます。128人のフローラは必要ありません。一回限りの行動（ハグやハイタッチなど）はロールプレイとは見なされません。",
        rule4_details_3: "代替アカウントを使用しないでください。",
        rule4_details_4: "タグ付けできない名前やニックネームを使用しないでください。あなたに話しかける方法が必要です！",
        rule4_details_5: "不適切なコンテンツを投稿しないでください、特に <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a> チャンネルでは。例としては、earrape、NSFWコンテンツ（ポルノ素材は許可されていません、たとえこれがファーリーサーバーであっても）、およびいかなるグループに対する害や憎悪を促進するメッセージが含まれます。常識を使用してください; モデレーターにはこのカテゴリに該当するメッセージを削除する権限があります。",
        rule5: "5. 足首は常に覆ってください。",
        rule5_details: "Basitin法、J.A., 389, c. E-62, s. 1 に従ってください。",
        rule6: "6. 会話には適切なチャンネルを使用してください。",
        rule7: "7. アートチャンネルのルール:",
        rule7_details: "詳細については <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a> を参照してください。",
        rule8: "8. 当社の懲戒システムを理解してください:",
        rule8_warnings: "警告: 警告は罰ではありません; 軽いリマインダーとして考えてください。警告が累積すると罰が科されます。",
        rule8_strikes: "罰:",
        strike_details_1: "最初の罰 (5 警告) | 結果: 地下牢で 12 時間",
        strike_details_2: "2回目の罰 (+3 警告) | 結果: 限定的なサーバーアクセスを伴う地下牢での 24 時間",
        strike_details_3: "3回目の罰 (+2 警告) | 結果: 行動の深刻さに応じて、永久的または一時的な禁止。",
    },
    be: {
        title: "Правілы сервера",
        rule1: "1. Дзейнічайце згодна з кіраўніцтвамі Discord.",
        rule1_details: "Гэтыя кіраўніцтвы прымяняюцца на ўсіх платформах Discord. Калі трэба, перагледзьце іх тут: <a href='https://discord.com/guidelines' class='btn'>Кіраўніцтвы Discord</a>",
        rule2: "2. Будзьце ўважлівыя да іншых удзельнікаў.",
        rule2_details_1: "Атрымлівайце асалоду ад кантэнту і часу разам, пазбягайце абразлівага паводзінаў або перадузятых адносін на аснове расы, ідэнтычнасці, рэлігіі і інш.",
        rule2_details_2: "Лёгкія жарты прыемныя, але выкарыстоўвайце здаровы сэнс і паважайце межы, асабліва з удзельнікамі, з якімі вы не з'яўляецеся блізкімі сябрамі.",
        rule3: "3. Паважайце персанал.",
        rule3_details_1: "Члены персаналу з'яўляюцца часткай супольнасці і працуюць над стварэннем дружалюбнай атмасферы.",
        rule3_details_2: "Дапамажыце ім, не паводзячыся глупа, і палегчыце іх працу.",
        rule4: "4. Не:",
        rule4_details_1: "Не рэкламуйце іншыя Discord серверы без адабрэння адміністрацыі. Нас не цікавіць далучэнне або прасоўванне несвязаных сервераў, такіх як 'Pawsome Fun House UwU'.",
        rule4_details_2: "Не ўдзельнічайце ў ролевых гульнях. Выкарыстанне персанажаў Twokinds як вашага імя або профільнага малюнка лічыцца ролевымі гульнямі. Мы не жадаем мець 128 Флор. Адзінакратныя дзеянні, такія як абдымкі або высокія пяць, не лічацца ролевымі гульнямі.",
        rule4_details_3: "Не выкарыстоўвайце альтэрнатыўныя акаўнты.",
        rule4_details_4: "Не выкарыстоўвайце імя або псеўданім, які немагчыма адзначыць. Нам патрэбны спосаб звяртацца да вас!",
        rule4_details_5: "Не размяшчайце непрымальны кантэнт, асабліва ў <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a>. Прыемныя прыклады ўключаюць earrape, NSFW кантэнт (порнаграфічныя матэрыялы не дазволены, нават калі гэта фурры-сервер), і паведамленні, якія прасоўваюць шкоду або нянавісць да любой групы. Выкарыстоўвайце здаровы сэнс; мадэратары маюць права выдаляць паведамленні, якія трапляюць у гэтую катэгорыю.",
        rule5: "5. Стопы павінны быць заўсёды накрытыя.",
        rule5_details: "Згодна з законам Basitin, J.A., 389, c. E-62, s. 1.",
        rule6: "6. Выкарыстоўвайце адпаведныя каналы для размоў.",
        rule7: "7. Правілы мастацкага канала:",
        rule7_details: "Звяртайцеся да <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a>",
        rule8: "8. Разбярыцеся з нашай сістэмай дысцыпліны:",
        rule8_warnings: "Папярэджанні: Папярэджанні не з'яўляюцца штрафамі; лічайце іх лёгкімі напамінамі. Накопліванне папярэджанняў прывядзе да штрафаў.",
        rule8_strikes: "Штрафы:",
        strike_details_1: "Першы штраф (5 папярэджанняў) | Пакаранне: 12 гадзін у зняволенні",
        strike_details_2: "Другі штраф (+3 папярэджанні) | Пакаранне: 24 гадзіны ў зняволенні з абмежаваным доступам да сервера пасля вызвалення.",
        strike_details_3: "Трэці штраф (+2 папярэджанні) | Пакаранне: Забарона, якая можа быць пастаяннай або часова залежна ад сур'ёзнасці дзеянняў.",
    },
    zh: {
        title: "服务器规则",
        rule1: "1. 遵守 Discord 的指导方针。",
        rule1_details: "这些指导方针适用于 Discord 的所有地方。如有需要，可以在这里查看：<a href='https://discord.com/guidelines' class='btn'>Discord 指导方针</a>",
        rule2: "2. 尊重其他成员。",
        rule2_details_1: "享受内容和共同度过的时光，避免基于种族、身份、宗教等的攻击性行为或偏见。",
        rule2_details_2: "轻松的玩笑可以，但请运用常识，尊重界限，特别是与不太亲密的成员相处时。",
        rule3: "3. 尊重工作人员。",
        rule3_details_1: "工作人员是社区的一部分，他们致力于维护一个友好的环境。",
        rule3_details_2: "通过不要做愚蠢的事情来帮助他们，简化他们的工作。",
        rule4: "4. 请勿：",
        rule4_details_1: "未经管理员批准，宣传其他 Discord 服务器。我们不感兴趣加入或推广与我们无关的服务器，如 'Pawsome Fun House UwU'。",
        rule4_details_2: "参与角色扮演。使用 Twokinds 角色作为您的名字或头像被视为角色扮演。我们不需要 128 个 Flora。一时的动作如拥抱或击掌不算角色扮演。",
        rule4_details_3: "使用备用账户。",
        rule4_details_4: "使用无法被 @ 提及的名字或昵称。我们需要一个称呼你的方式！",
        rule4_details_5: "发布不当内容，尤其是在 <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a> 频道中。例子包括 earrape、NSFW 内容（即使这是一个 furry 服务器，也不允许色情材料），以及任何针对某个群体的伤害或仇恨信息。请使用常识；管理员有权删除此类消息。",
        rule5: "5. 脚踝必须始终遮盖。",
        rule5_details: "根据 Basitin 法律，J.A., 389, c. E-62, s. 1。",
        rule6: "6. 使用适当的频道进行对话。",
        rule7: "7. 艺术频道规则：",
        rule7_details: "详情请参阅 <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a>",
        rule8: "8. 了解我们的纪律系统：",
        rule8_warnings: "警告：警告不是处罚；视为温和的提醒。累计警告将导致处罚。",
        rule8_strikes: "处罚：",
        strike_details_1: "第一次处罚 (5 次警告) | 后果：12 小时禁闭",
        strike_details_2: "第二次处罚 (+3 次警告) | 后果：释放后 24 小时禁闭，服务器访问受限。",
        strike_details_3: "第三次处罚 (+2 次警告) | 后果：禁令，可能是永久性的或暂时性的，取决于行为的严重程度。",
    },
    ko: {
        title: "서버 규칙",
        rule1: "1. Discord의 지침을 따르세요.",
        rule1_details: "이 지침은 Discord의 모든 곳에서 적용됩니다. 필요시 여기에서 확인하세요: <a href='https://discord.com/guidelines' class='btn'>Discord 지침</a>",
        rule2: "2. 다른 회원들을 존중하세요.",
        rule2_details_1: "컨텐츠와 함께 시간을 즐기되, 인종, 정체성, 종교 등을 기반으로 한 공격적 행동이나 편견을 피하세요.",
        rule2_details_2: "가벼운 농담은 괜찮지만, 상식과 경계를 존중하며, 특히 친하지 않은 회원들과는 더욱 조심하세요.",
        rule3: "3. 직원들을 존중하세요.",
        rule3_details_1: "직원들은 커뮤니티의 일원으로, 환영하는 환경을 유지하기 위해 노력하고 있습니다.",
        rule3_details_2: "바보 같은 행동을 하지 않고, 직원들의 일을 쉽게 해주세요.",
        rule4: "4. 다음을 하지 마세요:",
        rule4_details_1: "관리자의 승인 없이 다른 Discord 서버를 광고하지 마세요. 'Pawsome Fun House UwU'와 같은 관련 없는 서버에 가입하거나 홍보하는 것에는 관심이 없습니다.",
        rule4_details_2: "롤플레이에 참여하지 마세요. Twokinds 캐릭터를 이름이나 프로필 사진으로 사용하는 것은 롤플레이로 간주됩니다. 128개의 Flora는 필요 없습니다. 포옹이나 하이파이브와 같은 일회성 행동은 롤플레이로 간주되지 않습니다.",
        rule4_details_3: "대체 계정을 사용하지 마세요.",
        rule4_details_4: "멘션할 수 없는 이름이나 별명을 사용하지 마세요. 당신을 부를 방법이 필요합니다!",
        rule4_details_5: "부적절한 내용을 게시하지 마세요, 특히 <a href='https://discord.com/channels/359538295375659010/643518914038595614' class='btn'>#memes</a> 채널에서. 예를 들어, earrape, NSFW 콘텐츠 (포르노 자료는 허용되지 않으며, 이 서버가 furries 서버일지라도), 또는 어떤 그룹에 대한 해를 끼치거나 증오를 조장하는 메시지가 포함됩니다. 상식을 사용하세요; 관리자들은 이 카테고리에 해당하는 메시지를 삭제할 권한이 있습니다.",
        rule5: "5. 발목은 항상 가려야 합니다.",
        rule5_details: "Basitin 법률에 따라, J.A., 389, c. E-62, s. 1.",
        rule6: "6. 대화에는 적절한 채널을 사용하세요.",
        rule7: "7. 아트 채널 규칙:",
        rule7_details: "자세한 내용은 <a href='https://discord.com/channels/359538295375659010/776237678428422144/1071536905310707822' class='btn'>#keidran-promo</a>를 참조하세요.",
        rule8: "8. 우리의 징계 시스템을 이해하세요:",
        rule8_warnings: "경고: 경고는 징계가 아닙니다; 부드러운 알림으로 생각하세요. 경고가 누적되면 징계가 부과됩니다.",
        rule8_strikes: "징계:",
        strike_details_1: "첫 번째 징계 (5 경고) | 결과: 12시간 지하 감금",
        strike_details_2: "두 번째 징계 (+3 경고) | 결과: 24시간 지하 감금 및 해제 후 제한된 서버 접근.",
        strike_details_3: "세 번째 징계 (+2 경고) | 결과: 행동의 심각성에 따라 영구적 또는 임시 금지.",
    },
};
  